include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/l10n/intl/**
    - plugins/**
    - external_plugins/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true